---
name: docker-base
blueprint:
  name: docker/multi-image

## Overrides Hammer Global Config
main_user:
  name: Marcelo Correia
  description: Marcelo Correia
  github_user: marcelocorreia
  linkedin: https://www.linkedin.com/in/marcelocorreia
  docker_hub_user: marcelocorreia
  ansible_galaxy_user: marcelocorreia
  website: https://marcelo.correia.io
  email: marcelo@correia.io
  slack: https://correia-group.slack.com

tags:
  - terraform
  - module
  - aws
  - enc

readme:
  overview: |
    ### Docker Base images:
    - alpine
    - jessie-slim
    - buster-slim

  dockerfiles:
    - Dockerfile.alpine
    - Dockerfile.jessie-slim
    - Dockerfile.buster-slim

  usage: |
    ```bash
    $ docker run --rm marcelocorreia/base:alpine bash
    $ docker run --rm marcelocorreia/base:jessie-slim bash
    $ docker run --rm marcelocorreia/base:buster-slim bash
    ```
    ## Setting timezone
    ```bash
    $ docker run --rm -e TZ=Australia/Sydney marcelocorreia/base bash
    ```
    ### Extending
    ```Dockerfile
    FROM marcelocorreia/base:alpine
    ...
    ```
    ```Dockerfile
    FROM marcelocorreia/base:jessie-slim
    ...
    ```
    ```Dockerfile
    FROM marcelocorreia/base:buster-slim
    ...
    ```
    **Targets**
    ```bash
    $ make release
    $ make build
    $ make push
    $ make all-versions
    $ make current-version
    $ make next-version
    ```

  shields:
    - https://img.shields.io/docker/pulls/marcelocorreia/docker-base.svg
    - https://img.shields.io/github/languages/top/marcelocorreia/docker-base.svg
    - https://api.travis-ci.org/marcelocorreia/docker-base.svg?branch=master
    - https://img.shields.io/github/release/marcelocorreia/docker-base.svg?flat-square

  tldr:
    - '[Overview](#overview)'
    - '[Description](#description)'
    - '[Dockerfile](#dockerfile)'
    - '[Usage](#usage)'
    - '[License](#license)'

  licenses:
    - apache-license