---
name: marcelocorreia/base
github_user: marcelocorreia
git_repo: docker-base
docker_namespace: marcelocorreia
docker: https://hub.docker.com/u/marcelocorreia
github: https://github.com/marcelocorreia
dockerfile: Dockerfile
#logo: https://i2.wp.com/killscreen.com/wp-content/uploads/2016/08/bastion-gameplay.jpg?fit=700%2C396&ssl=1
#docs: https://your.docs.com
linkedin: https://www.linkedin.com/in/marcelocorreia/
#website: https://your.website.com
slack: https://correia-group.slack.com/
#email: marcelo@correia.io
blueprint: docker/image

overview: |
  Docker Base image

dockerfiles:
  - Dockerfile.alpine
  - Dockerfile.jessie-slim
  - Dockerfile.buster-slim
#extra_content: |
#  ### Extra

#description_file: path.to.description

#description: |
#  ### Description
#  Something cool

shields:
  - https://img.shields.io/docker/pulls/marcelocorreia/base.svg

tldr:
  - '[Overview](#overview)'
  - '[Description](#description)'
  - '[Dockerfile](#dockefile)'
  - '[License](#license)'

#usage_file: example/main.tf

licenses:
  - apache-license